### ISSUE TITLE
Cannot work locally without commit

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#11]
Must commit changes to remote watchdog_pi repository and then 
from github/watchdog_pi    execute antora --fetch build.yml   
it builds and then I can see the changes.

Even with this change in github/ocpn-manual/build.yml
```

site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:developer_guide.adoc

content:
  sources:
#    - url: https://github.com/rgleason/ocpn-dev-manual.git
    - url: ~/documents/github/ocpn-dev-manual
      branches: main   
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/leamas/shipdriver_pi.git
      branches: master
      edit_url: true
    - url: https://github.com/rgleason/watchdog_pi.git
      branches: master
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true



```

**Comment by rgleason** [comment]
The process that seems to work now from github/watchdog_pi

1. Make changes to the watchdog.adoc file locally using a test editor
2. git status
3. git add modules/      --whatever files have changes
4. git commit -am "wd chng"
5. git push origin master
6. antora --fetch build.yml    it builds and there is a progress bar.
7. then refresh the browser set to C:\Users\Rick\Documents\GitHub\watchdog_pi\build\site\index.html
8. which directs to  file:///C:/Users/Rick/Documents/GitHub/watchdog_pi/build/site/watchdog/2.4.24/watchdog.html#_f_how_does_watchdog_alert_me
8.

**Comment by rgleason** [comment]
This morning it occurred to me that using my text editor notepad++ and wanting to see the results, I've been pointing my brower at the html files which have to be regenerated on the remote sites!  Thus in order to see the changes and results in a page, I have to commit and push and then execute antora --fetch build.yml which is tedious and results in many ridiculous commits in the remote master branch.

I have to get this process under better control.  Should I git checkout -b "edit" branch and work on that?
Need some advice as this is new to me.

Also if I want to view changes locally to watchdog_pi documentation for example, 
I should load the firefox asciidoctor.js Live Preview  extension and point the browser at
file:///C:/Users/Rick/Documents/GitHub/watchdog_pi/modules/ROOT/pages/watchdog.adoc 
rather than 
C:\Users\Rick\Documents\GitHub\watchdog_pi\build\site\index.html

This does show the text and try to reformat it using some unknown css but it is not showing the images and does not look like the real thing.  So that is not goiing to work.

The html link is local to and is in github\watchdog_pi\build\site\index.html
so why isn''t that updating properly so I can view after local operations  like "antora build.yml" ?

I notice that often I have to also go to github\ocpn-plugins\ and execute "antora --fetch build.yml"
 because the index isn't updated.  I do not understan this system yet.  Why can't I do this locally?

The watchdog_pi  build.yml is

```
site:
  title: Watchdog Plugin Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  watchdog:ROOT:watchdog.adoc
content:
  sources:
    - url: https://github.com/rgleason/watchdog_pi.git
      branches: master
      edit_url: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
```

Is this ok or do I need to change something?

**Comment by rgleason** [comment]
The ocpn-plugins\build.yml is 

```
site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:developer_guide.adoc

content:
  sources:
    - url: ~/documents/github/ocpn-dev-manual
      branches: main   
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/leamas/shipdriver_pi.git
      branches: master
      edit_url: true
    - url: https://github.com/rgleason/watchdog_pi.git
      branches: master
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./docs

```

**Comment by rgleason** [comment]
github\ocpn-dev-manual  has no build.yml

**Comment by rgleason** [comment]
When I point the browser to

It shows in a side window
an https:// address to leamas.
![Screenshot (116)](https://user-images.githubusercontent.com/2363959/111908304-19731300-8a2f-11eb-8f21-41e66217942d.png)


But when I click on it the message says it is not valid.
Perhap the build.yml isn't configured completely yet?

**Comment by leamas** [comment]
> github\ocpn-dev-manual has no build.yml

Because it should not have.ocpn-dev-manual is a component, not a playbook. If you want to build it separately, just create a build.yml in an empty directory somewhere else and build there. When you do you could just build ocpn-dev-manual  or combine it with other ones, it depends on what's listed in the build.yml sources: part.

**Comment by leamas** [comment]
> , I've been pointing my brower at the html files which have to be regenerated on the remote sites!

when you build, there is a complete site available locally. Typically, standing in the playbook directory, you point your browser to build/site/index.html or docs/index.html

**Comment by leamas** [comment]
What's the status on this now? Please report back, preferably without screenshots ;)

**Comment by rgleason** [comment]
> when you build, there is a complete site available locally. Typically, standing in the playbook directory, you point your browser to build/site/index.html or docs/index.html, whichever exists.

Yes, the local site/index.html exists.
The problem is that it is not updating and changing when antora build.yml is run and I have to git add, git commit, git push,  then  antora  --fetch build.yml to get the html to be rewritten.

**Comment by rgleason** [comment]
I think sometimes (fairly often) I have to do that to ocpn-manuals,  issue a antora --fetch build.yml to make sure all the html is changed.

**Comment by leamas** [comment]
To fix this, you need something like build-loc.yml where you replace the http: urls in  build.ytml with the local directories on you box. This way, antora fetches tha data direct from your sources, committed or not.

Of course, you then need to invoke antora with this file , like `antora build-loc.ytml`

**Comment by rgleason** [comment]
Ok, yes. I will try that.

It is things like this that create hurdles for even plugin devs, and an Editor's Manual will be essential in my opinion.

**Comment by rgleason** [comment]
I am also wondering if I should be creating a new branch  git checkout -b edit to push the editing to, then make a PR back to main and merge?  Some of this gets a little more complex when we have the build.yml.

**Comment by leamas** [comment]
> I am also wondering if I should be creating a new branch git checkout -b edit to push the editing to, then make a PR back to main and merge? Some of this gets a little more complex when we have the build.yml.

Sure, it might be a good idea. But you don't need to make a PR, you can just merge it locally when you are done.

**Comment by leamas** [comment]
Also, see https://docs.antora.org/antora/2.2/playbook/author-mode/. Note that it recommends setting branch: to HEAD in build-loc.yml; it looks like the right thing to me.

**Comment by leamas** [comment]
have you got this in order?

**Comment by rgleason** [comment]
Made the Head change to build-loc.yml

```

Rick@Dart MINGW64 ~/documents/github/ocpn-manuals (main)
$ dir
build.yml  build-loc.yml  docs  LICENSE  Makefile  README.md

Rick@Dart MINGW64 ~/documents/github/ocpn-manuals (main)
$ antora build-loc.yml
Start page specified for site not found: ocpn-dev-manual:ROOT:developer_guide.adoc

```

**Comment by rgleason** [comment]
Have made a new yml   build-loc.yml and put local directory  in the url and watchdog documentation builds locally now.
```
site:
  title: Watchdog Plugin Manual
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  watchdog:ROOT:watchdog.adoc

content:
  sources:
    - url: ~/documents/github/watchdog_pi
      branches: master
      edit_url: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
	
```

What is confusing now is that, I added watchdog to the ocpn-manuals  and it does not seem to be building. moore on that later if I don't figure it out.

Closing

**Comment by rgleason** [comment]
I think I figured it out finally.  Did this

Made that change in ocpn-manuals  build-loc..yml
```

site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://leamas.github.io/ocpn-manuals/
  start_page:  ocpn-dev-manual:ROOT:developer_guide.adoc

content:
  sources:
    - url: ~/documents/github/ocpn-dev-manual
      branches: head
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/leamas/shipdriver_pi.git
      branches: master
      edit_url: true
    - url: ~/documents/github/watchdog_pi
      branches: master
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./docs

```
