### ISSUE TITLE
antora --fetch build.yml 

### ISSUE THREAD

**Issue by rgleason** [rgleason/ocpn-dev-manual#40]
from ocpn-dev-manual
antora --fetch build.yml works
antora build-loc.yml  doesn't.  "Start page specified for site not found: ocpn-dev-manual:ROOT:developer_guide.adoc"

```
Rick@Dart MINGW64 ~/documents/github/ocpn-manuals (main)
$ antora build-loc.yml
Start page specified for site not found: ocpn-dev-manual:ROOT:developer_guide.adoc

Rick@Dart MINGW64 ~/documents/github/ocpn-manuals (main)
$ antora --fetch build.yml
[fetch] https://github.com/leamas/shipdriver_pi.git [###########################################][fetch] https://github.com/leamas/ocpn-pi-docs.git  [###########################################][fetch] https://github.com/rgleason/watchdog_pi.git [###########################################]
Rick@Dart MINGW64 ~/documents/github/ocpn-manuals (main)
```

```
build-loc.yml

site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is seto
  url: https://leamas.github.io/ocpn-manuals/
  start_page: ocpn-dev-manual:ROOT:developer_guide.adoc

content:
  sources:
    - url: ~/documents/github/ocpn-dev-manual
      branches: head
      edit_url: false
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main
      edit_url: true
    - url: https://github.com/leamas/shipdriver_pi.git
      branches: master
      edit_url: true
    - url: ~/documents/github/watchdog_pi
      branches: master
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./docs

```

I've tried changing several things.

**Comment by leamas** [comment]
Well, just changing seldom works...   the xref is ocpn-dev-manual:ROOT:developer_guide.adoc.

  - does modules/ROOT/pages/developer_guide.adoc exist in  ~/documents/github/
  - Does ocpn-dev-manual  match the name:  line in ~/documents/github/antora.yml ?

**Comment by leamas** [comment]
This is a typical zulip issue. Closing

**Comment by rgleason** [comment]
name: ocpn-dev-manual
title: OpenCPN Developer Manual
version: '5.3.1'
nav: 
- modules/ROOT/nav.adoc

**Comment by leamas** [comment]
zulip, please

**Comment by rgleason** [comment]
So I guess it should be  

```
site:
  title: OpenCPN Developer Manual
  # the 404 page and sitemap files only get generated when the url property is set To
  url: https://leamas.github.io/ocpn-manuals/
  start_page: ocpn-dev-manual:ROOT:nav.adoc   <----


```
